### ISSUE TITLE
Access the strength value?

### ISSUE THREAD

**Issue by CraigsterJ** [rnadler/ng2-password-strength-bar#20]
I have the password strength bar working great, thanks. However I can't seem to see anywhere how I can use the strength value to do things like enable a Submit button. How can you access - possibly with an isValid sort of property or anything really?

Thanks!
Craig

**Comment by rnadler** [comment]
This is essentially the same request as #17.

**Comment by CraigsterJ** [comment]
I did see that – however it was just marked as an enhancement so I guess I was trying to ask it a different way. Is there any way to know that the password is valid and use it in angular?

**Comment by rnadler** [comment]
My preference is that the component provides a strength value (e.g. 0-100) and the client application decides the definition of "valid". I.e. the Submit button could be enabled at >= 80 for some purposes, but maybe >= 95 for others.

**Comment by CraigsterJ** [comment]
Absolutely - that sounds great! Do you have something like that?

Thanks!
Craig

**Comment by johnmckay-reward** [comment]
Not to be mean, but what's the point of this if you can't access the value?

**Comment by rnadler** [comment]
@jmkni, This project is just a simple password UI component. A popular solution that will provide you with deeper strength metircs is [zxcvbn](https://www.npmjs.com/package/zxcvbn).

**Comment by rnadler** [comment]
Feature added in v1.2.2 (PR #23)
